export const variants = {
  primary: "bg-blue-500 text-white",
  secondary: "bg-gray-500 text-white",
  success: "bg-green-500 text-white",
  danger: "bg-red-500 text-white",
  warning: "bg-yellow-500 text-white",
  info: "bg-teal-500 text-white",
  light: "bg-light-500 text-black",
  dark: "bg-dark-500 text-white",
  link: "bg-transparent text-blue-500",
  outlinePrimary: "border border-blue-500 text-blue-500",
  outlineSecondary: "border border-gray-500 text-gray-500",
  outlineSuccess: "border border-green-500 text-green-500",
  outlineDanger: "border border-red-500 text-red-500",
  outlineWarning: "border border-yellow-500 text-yellow-500",
  outlineInfo: "border border-teal-500 text-teal-500",
  outlineLight: "border border-light-500 text-light-500",
  outlineDark: "border border-dark-500 text-dark-500",
  large: "px-8 py-4 text-xl",
  outlineLarge: "border border-blue-500 text-blue-500 px-8 py-4 text-xl",
  small: "px-2 py-1 text-xs",
  outlineSmall: "border border-blue-500 text-blue-500 px-2 py-1 text-xs",
  disabled: "bg-gray-300 text-gray-700 cursor-not-allowed",
  github: "bg-gray-800 text-white border-b border-green-300",
  header:
    "inline-flex items-center text-sm px-4 py-2 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700",
};
